In [1]:
import pandas as pd

In [4]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [7]:
pd.merge(employees, departments, on = "DeptID") #Inner Join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [10]:
pd.merge(employees, departments, on = "DeptID", how = "left") #Left Join -> Include all rows of employees

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [16]:
pd.merge(employees, departments, on = "DeptID", how = "right") #Right Join -> Include all rows of departments

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [17]:
pd.merge(employees, departments, on = "DeptID", how = "outer") #Outer Join -> Include all rows

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [23]:
df1 = pd.DataFrame({"Name" : ["Alice", "Bob"], "Score" : [423, 634]})
df1

    Name  Score
0  Alice    423
1    Bob    634

In [24]:
df2 = pd.DataFrame({"Name" : ["Charlie", "David"], "Age" : [45, 78]})
df2

      Name  Age
0  Charlie   45
1    David   78

In [25]:
pd.concat([df1, df2])

      Name  Score   Age
0    Alice  423.0   NaN
1      Bob  634.0   NaN
0  Charlie    NaN  45.0
1    David    NaN  78.0

In [26]:
pd.concat([df1, df2], axis=1)

    Name  Score     Name  Age
0  Alice    423  Charlie   45
1    Bob    634    David   78